# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='blog_post',
        ),
    ]
